#!/bin/bash
#Usage: scriopt <dst File path>
#Example: script1 ~/CDPA/ 140.117.178.59
#checking files(ping-data)will save in $TargetPath

Time=$(date '+%Y-%m-%d_%k:%M')
#Hour=$(date '+%k')
Hour=14
Minut=$(date '+%M')
TargetPath=$1

#Count the range of 5 minuts in an hour
#Example: 0-4 = 0, 5-9 = 1, 10-14 = 2 ..., 55-59 = 11
Counter=$Minut
let Counter/=5
#echo $Counter
#echo "-----------------"

#test for count
#for i in `seq 0 59`;
#do
#	let Counter=$i
#	let Counter/=5
#	echo $Counter
#done

#reguler expression for checking file is correct
regex_day="([0-9]{4}-[0-9]{2}-[0-9]{2})"
regex="(ping_$regex_day\_[0-9]{1,2}\:[0-9]{1,2})"
#echo $regex

#reguler expression for "find" command to find ping-data
case $Counter in
1)
	regex2="(ping_$regex_day\_$Hour\:[0-4]{1})"
;;
2)
	regex2="(ping_$regex_day\_$Hour\:[5-9]{1})"
;;
3)
	regex2="(ping_$regex_day\_$Hour\:1[0-4]{1})"
;;
4)
	regex2="(ping_$regex_day\_$Hour\:1[5-9]{1})"
;;
5)
	regex2="(ping_$regex_day\_$Hour\:2[0-4]{1})"
;;
6)
	regex2="(ping_$regex_day\_$Hour\:2[5-9]{1})"
;;
7)
	regex2="(ping_$regex_day\_$Hour\:3[0-4]{1})"
;;
8)
	regex2="(ping_$regex_day\_$Hour\:3[5-9]{1})"
;;
9)
	regex2="(ping_$regex_day\_$Hour\:4[0-4]{1})"
;;
10)
	regex2="(ping_$regex_day\_$Hour\:4[5-9]{1})"
;;
11)
	regex2="(ping_$regex_day\_$Hour\:5[0-4]{1})"
;;
0)
	regex2="(ping_$regex_day\_$Hour\:5[5-9]{1})"
;;
*)
	echo "error in \$Counter"
;;
esac
echo $Counter
echo $regex2
echo "---------------"

cd $TargetPath

#Files=``
#echo $Files
#echo "----------------"

for file in *
do
#	echo ${file}
#	echo "$regex"
	if [[ ${file} =~ $regex2 ]]; then
		echo "Match file"
		cat $file >> tmp
	else
		echo "Doesn't match"
	fi
done
