#!/bin/bash
#Usage: scriopt <dst File path> <dst IP>
#Example: script1 ~/Ping/ 140.117.178.59
#ping data will save in $TargetPath/$DataFolder/$FileName
#Note: please run in background
Time=$(date '+%Y-%m-%d_%k:%M')
TargetPath=$1
DataFolder="PingData"
FileName="ping_$Time"
#echo $Time
#echo $TargetPath
#echo $DataFolder
#echo $FileName

#regex="(ping_[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{1,2}\:[0-9]{1,2})"
#echo $regex

cd $TargetPath
if [ -d $DataFolder ]; then 
	cd $DataFolder
else
	mkdir $DataFolder 
	cd $DataFolder
fi
#pring start time at the line 1 in the file
date '+TIME: %Y/%m/%d-%k:%M:%S' > "$FileName"
#ping 60 times per minut
ping -c 60 -i 1 $2 >> "$FileName"
